// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sheetstorm.Infrastructure.Persistence;

#nullable disable

namespace Sheetstorm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Einladung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EingeloestVonMusikerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ErstelltVonMusikerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KapelleID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VorgeseheRolle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EingeloestVonMusikerID");

                    b.HasIndex("ErstelltVonMusikerID");

                    b.HasIndex("KapelleID");

                    b.ToTable("Einladungen");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Kapelle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Kapellen");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.KapelleStimmenMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KapelleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stimme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KapelleId", "Instrument")
                        .IsUnique();

                    b.ToTable("KapelleStimmenMappings");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Mitgliedschaft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KapelleID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusikerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Rolle")
                        .HasColumnType("integer");

                    b.Property<string>("StimmenOverride")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KapelleID");

                    b.HasIndex("MusikerID", "KapelleID")
                        .IsUnique();

                    b.ToTable("Mitgliedschaften");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Musiker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Instrument")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordResetToken")
                        .IsUnique()
                        .HasFilter("\"PasswordResetToken\" IS NOT NULL");

                    b.ToTable("Musiker");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Notenblatt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StimmeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StimmeID");

                    b.ToTable("Notenblaetter");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MusikerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MusikerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stimme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrument")
                        .HasColumnType("text");

                    b.Property<Guid>("StueckID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StueckID");

                    b.ToTable("Stimmen");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stueck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arrangeur")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("KapelleID")
                        .HasColumnType("uuid");

                    b.Property<string>("Komponist")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MusikerID")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalDateiname")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Taktart")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Tempo")
                        .HasColumnType("integer");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tonart")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VeroeffentlichungsJahr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KapelleID");

                    b.HasIndex("MusikerID");

                    b.ToTable("Stuecke");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.StueckSeite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<int>("Seitennummer")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("StueckID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StueckID", "Seitennummer")
                        .IsUnique();

                    b.ToTable("StueckSeiten");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Einladung", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Musiker", "EingeloestVon")
                        .WithMany()
                        .HasForeignKey("EingeloestVonMusikerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sheetstorm.Domain.Entities.Musiker", "ErstelltVon")
                        .WithMany()
                        .HasForeignKey("ErstelltVonMusikerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sheetstorm.Domain.Entities.Kapelle", "Kapelle")
                        .WithMany("Einladungen")
                        .HasForeignKey("KapelleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EingeloestVon");

                    b.Navigation("ErstelltVon");

                    b.Navigation("Kapelle");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.KapelleStimmenMapping", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Kapelle", "Kapelle")
                        .WithMany("StimmenMappings")
                        .HasForeignKey("KapelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kapelle");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Mitgliedschaft", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Kapelle", "Kapelle")
                        .WithMany("Mitglieder")
                        .HasForeignKey("KapelleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sheetstorm.Domain.Entities.Musiker", "Musiker")
                        .WithMany("Mitgliedschaften")
                        .HasForeignKey("MusikerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kapelle");

                    b.Navigation("Musiker");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Notenblatt", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Stimme", "Stimme")
                        .WithMany("Notenblaetter")
                        .HasForeignKey("StimmeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stimme");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Musiker", "Musiker")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MusikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musiker");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stimme", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Stueck", "Stueck")
                        .WithMany("Stimmen")
                        .HasForeignKey("StueckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stueck");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stueck", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Kapelle", "Kapelle")
                        .WithMany("Stuecke")
                        .HasForeignKey("KapelleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sheetstorm.Domain.Entities.Musiker", "Musiker")
                        .WithMany()
                        .HasForeignKey("MusikerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kapelle");

                    b.Navigation("Musiker");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.StueckSeite", b =>
                {
                    b.HasOne("Sheetstorm.Domain.Entities.Stueck", "Stueck")
                        .WithMany("Seiten")
                        .HasForeignKey("StueckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stueck");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Kapelle", b =>
                {
                    b.Navigation("Einladungen");

                    b.Navigation("Mitglieder");

                    b.Navigation("StimmenMappings");

                    b.Navigation("Stuecke");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Musiker", b =>
                {
                    b.Navigation("Mitgliedschaften");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stimme", b =>
                {
                    b.Navigation("Notenblaetter");
                });

            modelBuilder.Entity("Sheetstorm.Domain.Entities.Stueck", b =>
                {
                    b.Navigation("Seiten");

                    b.Navigation("Stimmen");
                });
#pragma warning restore 612, 618
        }
    }
}
